name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
  sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make CFLAGS="-Wall -Wshadow -O2 -g -fsanitize=address,undefined" LDFLAGS="-fsanitize=address,undefined"
